// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyASUhFwKiFnKZ2CiDQK-YuZJzhkaT0TekI',
    appId: '1:319583910449:web:7dacc52fad2204d4f73310',
    messagingSenderId: '319583910449',
    projectId: 'taller1-amii',
    authDomain: 'taller1-amii.firebaseapp.com',
    databaseURL: 'https://taller1-amii-default-rtdb.firebaseio.com',
    storageBucket: 'taller1-amii.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4t480dSzQADIzmjlSMQ43yZbtq12QZRo',
    appId: '1:319583910449:android:030e9da5e296a920f73310',
    messagingSenderId: '319583910449',
    projectId: 'taller1-amii',
    databaseURL: 'https://taller1-amii-default-rtdb.firebaseio.com',
    storageBucket: 'taller1-amii.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvAjuFDtjxoD06lAy0Zub3EGgNN7_UUi0',
    appId: '1:319583910449:ios:304e3fae6f66cb7bf73310',
    messagingSenderId: '319583910449',
    projectId: 'taller1-amii',
    databaseURL: 'https://taller1-amii-default-rtdb.firebaseio.com',
    storageBucket: 'taller1-amii.appspot.com',
    iosBundleId: 'com.example.prueba2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAvAjuFDtjxoD06lAy0Zub3EGgNN7_UUi0',
    appId: '1:319583910449:ios:304e3fae6f66cb7bf73310',
    messagingSenderId: '319583910449',
    projectId: 'taller1-amii',
    databaseURL: 'https://taller1-amii-default-rtdb.firebaseio.com',
    storageBucket: 'taller1-amii.appspot.com',
    iosBundleId: 'com.example.prueba2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyASUhFwKiFnKZ2CiDQK-YuZJzhkaT0TekI',
    appId: '1:319583910449:web:189ffdc7d2293fd9f73310',
    messagingSenderId: '319583910449',
    projectId: 'taller1-amii',
    authDomain: 'taller1-amii.firebaseapp.com',
    databaseURL: 'https://taller1-amii-default-rtdb.firebaseio.com',
    storageBucket: 'taller1-amii.appspot.com',
  );

}